EDOLLAR:
  Monday:
  - - 00:00
    - '21:00'
  Tuesday:
  - - 00:00
    - '21:00'
  Wednesday:
  - - 00:00
    - '21:00'
  Thursday:
  - - 00:00
    - '21:00'
  Friday:
  - - 00:00
    - '21:00'
  Saturday: []
  Sunday: []
KR3:
  Monday: []
  Tuesday:
  - - 02:00
    - 06:45
  Wednesday:
  - - 02:00
    - 06:45
  Thursday:
  - - 03:00
    - 07:45
  Friday:
  - - 02:00
    - 06:45
  Saturday: []
  Sunday: []
JGB:
  Monday:
  - - 08:30
    - '21:00'
  - - 01:45
    - 02:02
  - - 05:30
    - 06:02
  Tuesday:
  - - 01:45
    - 02:02
  - - 05:30
    - 06:02
  - - 08:30
    - '21:00'
  Wednesday:
  - - 01:45
    - 02:02
  - - 05:30
    - 06:02
  - - 08:30
    - '21:00'
  Thursday:
  - - 01:45
    - 02:02
  - - 05:30
    - 06:02
  - - 08:30
    - '21:00'
  Friday:
  - - 01:45
    - 02:02
  - - 05:30
    - 06:02
  - - 08:30
    - '21:00'
  Saturday: []
  Sunday: []
