# Entries in this file determine trading hours
# This replaces the 'conservative' trading hours
#
# NOTE: these file will be replaced by this file private.private_config_trading_hours.yaml
# At a minimum, this must include a complete set of time zone specific trading hours
#
# We trade only in the intersection of:
#  1) instrument specific trading hours (see immediately below)
#  2) time zone specific trading hours (see later in file)
#  3) trading hours pulled from IB for a specific contract
#
# TRADING HOURS BY INSTRUMENT
#
# If an instrument is omitted, then we will use the time zone specific hours only
#
# We can encode time zones in this file in three different ways
# Replace the '..._example' with actual instrument names
# Firstly, by day. The following are lists per day, so we can encode multiple sessions per day
EDOLLAR_example:
  Monday:
    - - '15:00'
      - '21:00'
    - - '14:00'
      - '14:05'
  Tuesday: # With only one entry in the list only one session
  - - '16:00'
    - '21:00'
  Wednesday:
    - '17:00' # There is no need to nest lists for one session
    - '21:00'
  Thursday:
    - '18:00'
    - '21:00'
  Friday:
    - '19:00'
    - '21:00'
  Saturday: [] # if a day is omitted, like Sunday, we assume no trading on that day
## Or we can have just one list that applies to all days of the week
US2_example:
  - - '19:00'
    - '21:00'
  - - '18:05'
    - '18:10'
# Or we can have just one session per day for every day of the week
US10_example:
  - '19:00'
  - '21:00'
# TRADING HOURS BY TIME ZONE
#
# Again these can be in any of the formats shown above
# Time zones by region will be overwritten by market specific if available
# WARNING: If a time zone by region is not available, stuff will break
#          As it's important to know if region coding has changed
US/Central:
  - '15:00'
  - '20:00'
US/Eastern:
  - '14:00'
  - '19:00'
GB-Eire:
  - '09:00'
  - '16:00'
MET:
  - '08:00'
  - '15:00'
Japan:
  - '01:00'
  - '06:00'
HongKong:
  - '01:00'
  - '06:00'
Hongkong:
  - '01:00'
  - '06:00'
Australia/NSW:
  - '22:00'
  - '03:00'
