mr:
  conditioning_rule: momentum16
  mr_rule: mean_reversion
## this rule is used for the
trading_rules:
  momentum16:
     function: 'systems.provided.rules.ewmac.ewmac'
     data:
         - "rawdata.get_daily_prices"
         - "rawdata.daily_returns_volatility"
     other_args:
         Lfast: 16
         Lslow: 64
  mean_reversion:
      function: 'systems.provided.mr.rules.mr_rule'
      data:
        - "rawdata.get_hourly_prices"
        - "rawdata.get_daily_prices"
        - "rawdata.daily_returns_volatility"
      other_args:
        mr_span_days: 5
forecast_scalars:
  momentum16: 4.1
  mean_reversion: 20.0
use_attenuation:
  - 'mean_reversion'
buffer_method: 'none'
