name: Slow test (master)

on:
  schedule:
    - cron: '30 1 * * 0'

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ 3.8, 3.7 ]

    steps:

    - uses: actions/checkout@v3
      with:
        ref: "master"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install pip setuptools wheel
        pip install pytest
        pip install -r requirements.txt

    - name: Test with pytest
      run: |
        pytest --runslow  --disable-warnings

    #- name: Coverage report
    #  run: |
    #    coverage html
